"""Boltz regtest backend fixture.

Manages a BoltzExchange/regtest Docker Compose stack as a pytest fixture.
The stack ships a full Bitcoin Core + LND/CLN + Boltz backend + Boltz
client topology with channels already opened between the LN nodes; we
just need to (re)expose a few host ports so the host-running Electrum
and cashupayserver can talk to it.

Requirements (will skip the test loudly if missing):
  - `sudo` works without password prompt (NOPASSWD or already-cached)
  - `docker` and `docker compose` v2 are installed
  - The user has authorization to start containers

The host-side ports we map are fixed (not allocated dynamically) so the
test, the dev driver, and a manual `docker compose ps` are mutually
consistent.

  28443 -> bitcoind RPC      (host's :18443 is often already bound)
  39000 -> bitcoind ZMQ raw-tx
  39001 -> bitcoind ZMQ raw-block
  29001 -> boltz-backend-nginx (Boltz API alias)
  29735 -> lnd-1 P2P listen   (so host Electrum can open a channel here)
  9001  -> boltz-backend-nginx (also kept for compose default consumers)

`scripts` container helpers (lncli-sim, bitcoin-cli-sim-client, ...) are
invoked via `docker exec` so they hit the right Boltz internal config.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterator

import pytest

# Default to /tmp/boltz-regtest; tests can override via env.
DEFAULT_REPO_DIR = Path(os.environ.get("BOLTZ_REGTEST_DIR", "/tmp/boltz-regtest"))
REPO_URL = "https://github.com/BoltzExchange/regtest.git"

# Fixed host ports — see module docstring.
HOST_PORT_BITCOIND_RPC = 28443
HOST_PORT_BITCOIND_ZMQ_TX = 39000
HOST_PORT_BITCOIND_ZMQ_BLOCK = 39001
HOST_PORT_BOLTZ_API = 29001
HOST_PORT_LND1_P2P = 29735
HOST_PORT_CLN2_P2P = 29736  # cln-2 is Boltz's BOLT11 receiver; direct channel = 1-hop

OVERRIDE_TEMPLATE = """\
# Auto-generated by tests/fixtures/boltz_regtest.py — do not edit by hand.
# Override host-port bindings to avoid conflicts with whatever else is
# running on the dev box. We only expose what the host-side test stack
# actually consumes; everything else stays on the internal Docker network.
services:
  postgres:
    ports: !override []
  redis:
    ports: !override []
  bitcoind:
    ports: !override
      - {bitcoind_rpc}:18443
      - {zmq_tx}:29000
      - {zmq_block}:29001
  elementsd:
    ports: !override []
  esplora:
    ports: !override []
  electrs:
    ports: !override []
  electrs-liquid:
    ports: !override []
  cln-1:
    ports: !override []
  cln-2:
    ports: !override
      - {cln2_p2p}:9735  # so the host-running Electrum can open a direct channel here
  lnd-1:
    ports: !override
      - {lnd1_p2p}:9735
  lnd-2:
    ports: !override []
  lnd-3:
    ports: !override []
  boltz-backend-nginx:
    ports:
      - {boltz_api}:9001
  boltz-web-app:
    ports: !override []
  boltz-client:
    ports: !override []
  anvil:
    ports: !override []
  otterscan:
    ports: !override []
  nbxplorer:
    ports: !override []
  arkd-wallet:
    ports: !override []
  arkd:
    ports: !override []
  fulmine:
    ports: !override []
"""


@dataclass
class BoltzRegtestHandle:
    """Handle on a running Boltz regtest stack."""
    repo_dir: Path
    api_url: str = f"http://127.0.0.1:{HOST_PORT_BOLTZ_API}"
    bitcoind_rpc_host: str = "127.0.0.1"
    bitcoind_rpc_port: int = HOST_PORT_BITCOIND_RPC
    lnd1_p2p_host: str = "127.0.0.1"
    lnd1_p2p_port: int = HOST_PORT_LND1_P2P
    lnd1_pubkey: str = ""
    cln2_p2p_host: str = "127.0.0.1"
    cln2_p2p_port: int = HOST_PORT_CLN2_P2P
    cln2_pubkey: str = ""  # cln-2 is the destination Boltz uses for its BOLT11s
    _cookie_cache: str = ""

    def docker_compose(self, *args: str, check: bool = True, timeout: int = 60) -> subprocess.CompletedProcess[str]:
        """Run a docker-compose command inside the regtest repo dir."""
        cmd = ["sudo", "-n", "docker", "compose", *args]
        return subprocess.run(cmd, cwd=str(self.repo_dir), capture_output=True, text=True,
                              check=check, timeout=timeout)

    def docker_exec(self, container: str, *args: str, check: bool = True, timeout: int = 60) -> subprocess.CompletedProcess[str]:
        """Run an in-container command via docker exec."""
        cmd = ["sudo", "-n", "docker", "exec", container, *args]
        return subprocess.run(cmd, capture_output=True, text=True, check=check, timeout=timeout)

    def scripts(self, shell_cmd: str, timeout: int = 60) -> str:
        """Run a shell command inside the scripts container with utils.sh sourced."""
        res = self.docker_exec("boltz-scripts", "bash", "-c",
                               f"source /etc/profile.d/utils.sh && {shell_cmd}",
                               check=False, timeout=timeout)
        if res.returncode != 0:
            raise RuntimeError(
                f"boltz-scripts: `{shell_cmd}` failed (rc={res.returncode})\n"
                f"stdout: {res.stdout}\nstderr: {res.stderr}"
            )
        return res.stdout.strip()

    def mine_blocks(self, n: int) -> None:
        """Mine n blocks via boltz-scripts."""
        self.scripts(f"bitcoin-cli-sim-client -generate {n}")

    # Quack-compatible with BitcoindHandle.mine() so existing electrum helpers
    # that take a BitcoindHandle work with us via a shim.
    def mine(self, n: int = 1) -> None:
        self.mine_blocks(n)

    def bitcoind_cookie(self, refresh: bool = False) -> str:
        """Read the bitcoind cookie from the container. Cached; refresh=True
        re-reads (the file changes when bitcoind restarts)."""
        if not refresh and self._cookie_cache:
            return self._cookie_cache
        res = self.docker_exec("boltz-bitcoind", "cat", "/app/bitcoin/regtest/.cookie")
        self._cookie_cache = res.stdout.strip()
        return self._cookie_cache

    def bitcoind_rpc(self, method: str, *params: Any, timeout: int = 30) -> Any:
        """Talk to Boltz bitcoind from the host via cookie auth."""
        import urllib.request
        from base64 import b64encode
        cookie = self.bitcoind_cookie()
        user, _, password = cookie.partition(":")
        body = json.dumps({"jsonrpc": "1.0", "id": "fixture", "method": method, "params": list(params)}).encode()
        auth = b64encode(f"{user}:{password}".encode()).decode()
        req = urllib.request.Request(
            f"http://{self.bitcoind_rpc_host}:{self.bitcoind_rpc_port}/",
            data=body,
            headers={"Authorization": f"Basic {auth}", "Content-Type": "text/plain"},
        )
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            data = json.loads(resp.read())
        if data.get("error"):
            raise RuntimeError(f"bitcoind RPC {method}: {data['error']}")
        return data.get("result")

    def send_to_address(self, address: str, sats: int) -> str:
        """Send sats from the Boltz miner wallet to an arbitrary address.
        Used by the test to fund Electrum's on-chain wallet. Returns txid."""
        btc = f"{sats / 100_000_000:.8f}"
        out = self.scripts(f"bitcoin-cli-sim-client -named sendtoaddress address={address} amount={btc}")
        return out

    def lnd1_payinvoice(self, bolt11: str, timeout: int = 90) -> str:
        """Pay a BOLT11 from lnd-1 (Boltz's customer-side node).

        lncli blocks until the LN HTLC settles, which for a Boltz hold
        invoice means until the on-chain claim has been completed. With
        timeout > 0 we still get partial output on success/failure."""
        return self.scripts(f"lncli-sim 1 payinvoice -f {bolt11}", timeout=timeout)

    def fetch_lnd1_info(self) -> dict:
        """Returns the JSON from `lncli-sim 1 getinfo`."""
        raw = self.scripts("lncli-sim 1 getinfo")
        return json.loads(raw)

    def fetch_cln2_info(self) -> dict:
        """Returns the JSON from `lightning-cli-sim 2 getinfo`."""
        raw = self.scripts("lightning-cli-sim 2 getinfo")
        return json.loads(raw)


def _ensure_repo(repo_dir: Path) -> None:
    if not repo_dir.exists() or not (repo_dir / "docker-compose.yml").exists():
        if shutil.which("git") is None:
            raise RuntimeError("git missing; cannot clone Boltz regtest")
        repo_dir.parent.mkdir(parents=True, exist_ok=True)
        subprocess.check_call(["git", "clone", "--depth", "1", REPO_URL, str(repo_dir)],
                              stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)


def _write_override(repo_dir: Path) -> None:
    target = repo_dir / "docker-compose.override.yml"
    target.write_text(OVERRIDE_TEMPLATE.format(
        bitcoind_rpc=HOST_PORT_BITCOIND_RPC,
        zmq_tx=HOST_PORT_BITCOIND_ZMQ_TX,
        zmq_block=HOST_PORT_BITCOIND_ZMQ_BLOCK,
        lnd1_p2p=HOST_PORT_LND1_P2P,
        cln2_p2p=HOST_PORT_CLN2_P2P,
        boltz_api=HOST_PORT_BOLTZ_API,
    ))


def _check_docker_available() -> str | None:
    """Returns None if docker+compose+sudo work, otherwise a skip reason."""
    if shutil.which("sudo") is None:
        return "sudo missing"
    if shutil.which("docker") is None:
        return "docker missing"
    # sudo -n: non-interactive. If a password is needed, sudo exits 1.
    res = subprocess.run(["sudo", "-n", "docker", "version"], capture_output=True, text=True, timeout=10)
    if res.returncode != 0:
        return f"`sudo docker version` failed: {res.stderr.strip()[:100]}"
    res = subprocess.run(["sudo", "-n", "docker", "compose", "version"], capture_output=True, text=True, timeout=10)
    if res.returncode != 0:
        return f"`sudo docker compose version` failed: {res.stderr.strip()[:100]}"
    return None


def start_boltz_regtest(repo_dir: Path | None = None, ready_timeout: int = 180) -> BoltzRegtestHandle:
    """Bring up the Boltz regtest stack and return a handle once it's healthy.

    Idempotent: if the stack is already running, this re-applies the
    override (which may restart containers if their config changed) and
    just verifies health.
    """
    if repo_dir is None:
        repo_dir = DEFAULT_REPO_DIR
    _ensure_repo(repo_dir)
    _write_override(repo_dir)

    handle = BoltzRegtestHandle(repo_dir=repo_dir)
    # Bring up. `compose up -d` reuses containers whose config didn't
    # change, restarts the ones that did, creates the missing ones.
    handle.docker_compose("up", "-d", "--remove-orphans", timeout=600)

    # Wait for the Boltz API to respond with healthy pair info.
    deadline = time.monotonic() + ready_timeout
    last_err = ""
    while time.monotonic() < deadline:
        try:
            import urllib.request
            with urllib.request.urlopen(f"{handle.api_url}/v2/swap/reverse", timeout=3) as resp:
                pair = json.loads(resp.read())
            if pair.get("BTC", {}).get("BTC", {}).get("limits", {}).get("minimal", 0) > 0:
                break
            last_err = f"unexpected pair info shape: {pair}"
        except Exception as e:
            last_err = str(e)
        time.sleep(2)
    else:
        raise TimeoutError(f"Boltz API not healthy after {ready_timeout}s; last error: {last_err}")

    # The `scripts` helper container has a race with bitcoind init on first
    # start (it chmods bitcoind's regtest dir before bitcoind has created
    # the .lock file). It's `restart: no` so it stays exited. Restart it
    # once bitcoind is healthy. Idempotent if it's already running.
    try:
        handle.docker_compose("start", "scripts", timeout=30)
    except Exception:
        pass

    # Backend may have been restarted; its CLN connection sometimes drops
    # the first time the bitcoind cookie rotates. Restarting boltz-backend
    # re-reads the cookie. Cheap insurance.
    try:
        handle.docker_compose("restart", "boltz-backend", timeout=60)
        time.sleep(5)
    except Exception:
        pass

    # Wait for scripts to be running (start is async)
    deadline = time.monotonic() + 30
    while time.monotonic() < deadline:
        ps = subprocess.run(
            ["sudo", "-n", "docker", "ps", "--filter", "name=boltz-scripts",
             "--format", "{{.State}}"],
            capture_output=True, text=True, timeout=10,
        )
        if "running" in ps.stdout:
            break
        time.sleep(1)
    else:
        raise RuntimeError("boltz-scripts container failed to start; check `docker logs boltz-scripts`")

    # Read lnd-1 + cln-2 pubkeys for channel-opening.
    info = handle.fetch_lnd1_info()
    handle.lnd1_pubkey = info["identity_pubkey"]
    cln2_info = handle.fetch_cln2_info()
    handle.cln2_pubkey = cln2_info["id"]

    return handle


def stop_boltz_regtest(handle: BoltzRegtestHandle) -> None:
    """Full teardown: `docker compose down --volumes`. Slow (~30s)."""
    try:
        handle.docker_compose("down", "--volumes", timeout=300, check=False)
    except Exception as e:
        print(f"[boltz_regtest] teardown error (non-fatal): {e}", file=sys.stderr)


@pytest.fixture(scope="session")
def boltz_regtest() -> Iterator[BoltzRegtestHandle]:
    """Session-scoped: one Boltz stack for the whole pytest run, torn down at end."""
    skip = _check_docker_available()
    if skip:
        pytest.skip(f"Boltz regtest fixture unavailable: {skip}")
    handle = start_boltz_regtest()
    try:
        yield handle
    finally:
        stop_boltz_regtest(handle)
